Repository RooftopAcademy/roofstore, pull requests merged in 2021-11, with the labels that each got.

#57 ProductPage segunda parte
  src/App.css
  src/Pages/Public/ProductPage/Block/BreadcrumbBlock.js
  src/Pages/Public/ProductPage/Block/FeaturedProductsBlock.js
  src/Pages/Public/ProductPage/Block/GarantiaBlock.js
  src/Pages/Public/ProductPage/Block/PaymentBlock.js
  src/Pages/Public/ProductPage/Block/ProductReviewsBlock.js
  src/Pages/Public/ProductPage/Block/QuestionAndAnswerBlock.js
  src/Pages/Public/ProductPage/Component/AProductBanner.js
  src/Pages/Public/ProductPage/Component/AutoGrowTextAreaComponent.js
  src/Pages/Public/ProductPage/Component/KeywordInformationButtonComponent.js
  src/Pages/Public/ProductPage/Component/OpinionComponent.js
  src/Pages/Public/ProductPage/Component/QAComponent.js
  src/Pages/Public/ProductPage/Component/ToogleButtons.js
  src/Pages/Public/ProductPage/ProductPage.js
  src/Pages/Public/ProductPage/mockData.js
Labels: size: 20

#74 Feature 58 redirect to main page
  src/Blocks/Navbar.js
  src/Blocks/Navbar.test.js
  src/Components/TextLink.js
Labels: size: 1

#77 Feature search help
  public/forget.svg
  src/App.css
  src/Components/SearchHelp.js
  src/Components/SearchHelp.test.js
  src/Components/SearchHelp/Components/SuggestedResultItem.js
  src/Components/SearchHelp/suggestedResultsData.js
  src/Components/SearchHelp/svgIcons.js
Labels: size: 13

#78 Feature 69 shopping history page
  src/App.css
  src/App.js
  src/Blocks/Footer/FooterMenu.js
  src/Pages/ShoppingHistoryPage/ShoppingHistoryData.js
  src/Pages/ShoppingHistoryPage/ShoppingHistoryPage.js
  src/Pages/ShoppingHistoryPage/ShoppingHistoryPage.test.js
  src/Pages/ShoppingHistoryPage/shoppingHistoryItem.js
Labels: size: 5

#87 Feature 66 info financial user page
  public/imgBc.jpg
  public/imgDownProducts.jpg
  src/App.css
  src/App.js
  src/Blocks/Footer.js
  src/Blocks/Footer/FooterInfo.js
  src/Blocks/Navbar.js
  src/Layouts/TextPageLayout.js
  src/Layouts/TextPageLayout.test.js
  src/Pages/Public/InfoFinancialUserPage.js
  src/Pages/Public/InfoFinancialUserPage.test.js
Labels: size: 3

#79 Feature Defensa Consumidor Page
  src/App.css
  src/App.js
  src/Blocks/Footer/FooterInfo.js
  src/Pages/Public/DefensaConsumidor/DefensaConsumidorBlock.js
  src/Pages/Public/DefensaConsumidor/DefensaConsumidorItem.js
  src/Pages/Public/DefensaConsumidor/DefensaConsumidorItem.test.js
  src/Pages/Public/DefensaConsumidor/DefensaConsumidorPage.js
  src/Pages/Public/DefensaConsumidor/DefensaConsumidorPage.test.js
  src/Pages/Public/DefensaConsumidor/__snapshots__/DefensaConsumidorItem.test.js.snap
Labels: size: 3

#82 Fix InfoVotation
  src/Components/InfoVotation.js
Labels: size: 0.5

#83 MenuMobile links
  src/Blocks/MenuMobile/MenuMobile.js
  src/Blocks/MenuMobile/MenuMobile.test.js
Labels: size: 2

#84 Feature 64 text page layout
  src/App.css
  src/Blocks/Navbar.js
Labels: size: 5

#85 Feature 65 terminos y condiciones page
  src/App.js
  src/Blocks/Footer/FooterInfo.js
  src/Blocks/Footer/FooterInfo.test.js
  src/Blocks/Navbar.js
  src/Pages/TermsAndConditionsPage/TermsAndConditionsPage.js
  src/Pages/TermsAndConditionsPage/TermsAndConditionsPage.test.js
  src/Pages/TermsAndConditionsPage/info.js
Labels: size: 5
