Repository RooftopAcademy/roofstore, pull requests merged in 2021-12, with the labels that each got.

#102 Fix 93 boton crear cuenta
  src/Pages/HomePage/CreateAccountCard.js
  src/Pages/HomePage/CreateAccountCard.test.js
Labels: size: 1

#105 Fix 95 advertisement card
  src/Pages/HomePage/Advertisement.js
  src/Pages/HomePage/Advertisement.test.js
  src/Pages/HomePage/Data/advertisementsData.js
Labels: size: 1

#112 Feature help page
  src/App.js
  src/Pages/Public/HelpPage.jsx
  src/Pages/Public/HelpPage.test.js
  src/Pages/Public/HelpPage/HelpBlock.jsx
  src/Pages/Public/HelpPage/HelpPageCategory.jsx
  src/Pages/Public/HelpPage/categoriesData.jsx
  src/Pages/Public/HelpPage/categoryBlocksData.jsx
Labels: size: 5

#108 Feature 94 official stores
  src/App.css
  src/App.js
  src/Components/SearchHelp/svgIcons.js
  src/Pages/Public/OfficialStoresPage.jsx
  src/Pages/Public/OfficialStoresPage.test.js
  src/Pages/Public/OfficialStoresPage/InputStores.jsx
  src/Pages/Public/OfficialStoresPage/OfficialStoresBlock.jsx
  src/Pages/Public/OfficialStoresPage/StoreCard.jsx
  src/Pages/Public/OfficialStoresPage/officialStoresData.jsx
Labels: size: 8

#107 Feature carrito no autenticado
  src/App.js
  src/Pages/Public/CartUnloggedPage.js
  src/Pages/Public/CartUnloggedPage.test.js
Labels: size: 3

#106 Fix 96 categorias populares
  src/App.js
  src/Blocks/MenuMobile/MenuMobile.test.js
  src/Pages/Public/HomePage.js
  src/Pages/Public/HomePage.test.js
Labels: size: 1

#146 fix: remove domain for icon paths in ChooseRootCategory.js
  src/Pages/PublishingProcess/ChooseRootCategory.js
Labels: bug, size: 2

#134 Fix 120 remove universal selector
  src/App.css
Labels: bug, size: 1

#142 Fix 121 build warnings
  src/Components/SearchHelp/svgIcons.js
  src/Pages/CartPage/CartItem.js
  src/Pages/Public/HelpPage.jsx
  src/Pages/Public/HelpPage/HelpBlock.jsx
  src/Pages/Public/HelpPage/HelpPageCategory.jsx
  src/Pages/Public/InfoFinancialUserPage.js
  src/Pages/Public/OfficialStoresPage.jsx
  src/Pages/Public/OfficialStoresPage/InputStores.jsx
  src/Pages/Public/OfficialStoresPage/OfficialStoresBlock.jsx
  src/Pages/Public/OfficialStoresPage/StoreCard.jsx
  src/Pages/Public/ProductPage/Block/QuestionAndAnswerBlock.js
  src/Pages/Public/ProductPage/Component/Badge.js
  src/Pages/Public/ProductPage/Component/Benefit.js
  src/Pages/Public/ProductPage/Component/SeeMore.js
  src/Pages/PublishingProcess/ChooseRootCategory.js
Labels: size: 2

#143 Fix 131 title and icon page
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
Labels: size: 1

#145 Fix 129 links footer
  src/Blocks/Footer/FooterHeader.js
  src/Blocks/Footer/FooterHeader.test.js
  src/Blocks/Footer/FooterInfo.js
  src/Blocks/Footer/FooterInfo.test.js
  src/Blocks/Footer/FooterLogin.js
  src/Blocks/Footer/FooterLogin.test.js
  src/Blocks/Footer/FooterMenu.js
  src/Blocks/Footer/FooterMenu.test.js
Labels: bug, size: 2

#155 Fix 153 icons
  src/Components/Icon.js
  src/Pages/Public/RegisterPage.js
Labels: bug, size: 0.5

#174 button style changed
  src/Blocks/MenuMobile/MenuMobile.js
Labels: size: 0.5

#169 fix-user-avatar
  public/user-avatar.png
  src/Blocks/MenuMobile/MenuMobile.js
Labels: size: 2

#171 fix-banner-detalles
  public/raid-banner.png
  public/raid-info-banner.png
  src/Pages/Public/ProductPage/Component/AProductBanner.js
Labels: size: 2

#175 redirect to "sell/item-title"
  src/Pages/PublishingProcess/ChooseRootCategory.js
Labels: size: 0.5

#170 fix-link-tiendas
  src/App.js
Labels: size: 1

#182 Fixed 179; Changed navbar test
  src/Blocks/Navbar.test.js
Labels: size: 0.5

#181 Fix 180; Changed background image to url more dynamic
  src/App.css
Labels: size: 0.5

#192 Fix 165 payment info icon
  public/credit-card.svg
  src/Pages/HomePage/PaymentInfo.js
Labels: size: 0.5

#190 added yar.lock in gitignore
  .gitignore
Labels: size: 0.5

#178 Fix 161 scroll up
  src/App.js
  src/Components/ScrollTop.js
Labels: size: 3

#191 eslint-config
  .eslintrc.json
  .prettierrc.json
  package.json
Labels: size: 5

#196 Feature 118 cuantity cart modal
  package.json
  src/App.css
  src/Pages/CartPage/CartItem.js
  src/Pages/CartPage/ModalCartInputQuantity.js
  src/Pages/CartPage/ModalCartQuantity.js
  src/Pages/CartPage/ModalCartQuantity.test.js
  src/Pages/CartPage/QuantitiesItems.js
Labels: size: 8

#202 Fix 185 help page
  src/App.css
  src/Pages/Public/HelpPage.jsx
Labels: size: 1

#198 Feature 151 navigation page
  src/App.css
  src/App.js
  src/Blocks/MenuMobile/MenuMobile.js
  src/Blocks/MenuMobile/MenuMobile.test.js
  src/Components/Icon.js
  src/Components/InteractionProductItem.js
  src/Components/InteractionProductItem.test.js
  src/Components/SwitchButton.js
  src/Pages/HomePage/PaymentInfo.js
  src/Pages/Public/AdminNavigationPage.js
  src/Pages/Public/AdminNavigationPage.test.js
  src/Pages/Public/NavigationPage.js
  src/Pages/Public/NavigationPage.test.js
  src/Pages/Public/NavigationPage/navigationData.js
Labels: size: 8

#203 feature: pagina de preguntas despues de la compra
  package.json
  src/App.css
  src/App.js
  src/Components/FormInput.jsx
  src/Components/Icon.js
  src/Pages/Public/MessengerServicePage/Message.js
  src/Pages/Public/MessengerServicePage/MessengerServicePage.js
  src/Pages/Public/MessengerServicePage/mesaggesList.js
  yarn.lock
Labels: size: 13

#197 Feature 148 favourites page
  src/App.css
  src/App.js
  src/Components/Icon.js
  src/Components/InteractionProductItem.js
  src/Pages/Public/FavouritesPage/FavouritesPage.js
  src/Pages/Public/FavouritesPage/FavouritesPage.test.js
  src/Pages/Public/FavouritesPage/favouritesData.js
Labels: size: 8
